payload:
  - PROCESS-NAME,com.milink.service
  - PROCESS-NAME,com.android.printspooler
  - PROCESS-NAME,com.miui.hybrid
  - PROCESS-NAME,com.xiaomi.drivemode
  - PROCESS-NAME,com.qualcomm.qti.qdma
  - PROCESS-NAME,com.cn21.ecloud
  - PROCESS-NAME,com.xunmeng.pinduoduo
  - PROCESS-NAME,com.flyersoft.moonreaderp
  - PROCESS-NAME,com.tencent.mobileqq
  - PROCESS-NAME,com.miui.player
  - PROCESS-NAME,com.miui.phrase
  - PROCESS-NAME,com.android.pacprocessor
  - PROCESS-NAME,com.yitong.mbank.psbc
  - PROCESS-NAME,com.xinhang.mobileclient
  - PROCESS-NAME,com.android.hotspot2.osulogin
  - PROCESS-NAME,com.miui.compass
  - PROCESS-NAME,com.miui.contentcatcher
  - PROCESS-NAME,com.miui.guardprovider
  - PROCESS-NAME,com.miui.smarttravel
  - PROCESS-NAME,com.coolapk.market
  - PROCESS-NAME,com.miui.newhome
  - PROCESS-NAME,com.miui.calculator
  - PROCESS-NAME,io.github.qauxv
  - PROCESS-NAME,miui.systemui.plugin
  - PROCESS-NAME,com.android.contacts
  - PROCESS-NAME,com.unionpay.tsmservice.mi
  - PROCESS-NAME,com.android.deskclock
  - PROCESS-NAME,com.miui.micloudsync
  - PROCESS-NAME,com.baidu.tieba
  - PROCESS-NAME,com.miui.wmsvc
  - PROCESS-NAME,com.newcapec.mobile.ncp
  - PROCESS-NAME,com.sgcc.wsgw.cn
  - PROCESS-NAME,com.xiaomi.finddevice
  - PROCESS-NAME,bxyz.lsr
  - PROCESS-NAME,com.yueme.itv
  - PROCESS-NAME,com.qidian.QDReader
  - PROCESS-NAME,com.android.updater
  - PROCESS-NAME,com.android.nfc
  - PROCESS-NAME,com.duokan.phone.remotecontroller
  - PROCESS-NAME,com.miui.cloudservice
  - PROCESS-NAME,flar2.devcheck
  - PROCESS-NAME,com.miui.notification
  - PROCESS-NAME,com.miui.nextpay
  - PROCESS-NAME,com.miui.voicetrigger
  - PROCESS-NAME,com.xiaomi.otrpbroker
  - PROCESS-NAME,com.android.carrierdefaultapp
  - PROCESS-NAME,com.miui.misound
  - PROCESS-NAME,com.xiaomi.market
  - PROCESS-NAME,com.modemdebug
  - PROCESS-NAME,com.chaoxing.mobile
  - PROCESS-NAME,com.okinc.okex.gp
  - PROCESS-NAME,com.android.statementservice
  - PROCESS-NAME,cn.wps.moffice_eng.xiaomi.lite
  - PROCESS-NAME,com.xiaomi.payment
  - PROCESS-NAME,com.miui.home
  - PROCESS-NAME,com.cainiao.wireless
  - PROCESS-NAME,com.miui.analytics
  - PROCESS-NAME,com.android.bips
  - PROCESS-NAME,com.xiaomi.powerchecker
  - PROCESS-NAME,com.xiaomi.account
  - PROCESS-NAME,com.xiaomi.location.fused
  - PROCESS-NAME,com.alicloud.databox
  - PROCESS-NAME,com.miui.virtualsim
  - PROCESS-NAME,com.android.quicksearchbox
  - PROCESS-NAME,com.miui.weather2
  - PROCESS-NAME,com.max.xiaoheihe
  - PROCESS-NAME,com.xiaomi.smarthome
  - PROCESS-NAME,com.taobao.idlefish
  - PROCESS-NAME,com.xiaomi.aiasst.service
  - PROCESS-NAME,com.android.mms
  - PROCESS-NAME,com.miui.fm
  - PROCESS-NAME,com.miui.vsimcore
  - PROCESS-NAME,com.miui.daemon
  - PROCESS-NAME,com.android.bankabc
  - PROCESS-NAME,com.android.thememanager
  - PROCESS-NAME,com.qualcomm.embms
  - PROCESS-NAME,com.xiaomi.simactivate.service
  - PROCESS-NAME,com.android.camera
  - PROCESS-NAME,com.iflytek.inputmethod.miui
  - PROCESS-NAME,com.miui.bugreport
  - PROCESS-NAME,com.android.incallui
  - PROCESS-NAME,com.android.calendar
  - PROCESS-NAME,com.android.settings
  - PROCESS-NAME,com.xiaomi.mirror
  - PROCESS-NAME,com.jingdong.app.mall
  - PROCESS-NAME,com.android.soundrecorder
  - PROCESS-NAME,com.xiaomi.joyose
  - PROCESS-NAME,com.miui.fmservice
  - PROCESS-NAME,air.tv.douyu.android
  - PROCESS-NAME,com.mipay.wallet
  - PROCESS-NAME,com.qualcomm.wfd.service
  - PROCESS-NAME,com.tencent.mm
  - PROCESS-NAME,com.miui.cleanmaster
  - PROCESS-NAME,com.miui.securitycore
  - PROCESS-NAME,com.miui.systemAdSolution
  - PROCESS-NAME,io.legado.app.release
  - PROCESS-NAME,com.xiaomi.ab
  - PROCESS-NAME,com.xiaomi.vipaccount
  - PROCESS-NAME,com.android.phone
  - PROCESS-NAME,com.fido.xiaomi.uafclient
  - PROCESS-NAME,com.sinovatech.unicom.ui
  - PROCESS-NAME,com.miui.core
  - PROCESS-NAME,com.android.captiveportallogin
  - PROCESS-NAME,com.google.android.printservice.recommendation
  - PROCESS-NAME,com.miui.packageinstaller
  - PROCESS-NAME,com.android.fileexplorer
  - PROCESS-NAME,com.mi.health
  - PROCESS-NAME,com.xiaomi.aiasst.vision
  - PROCESS-NAME,com.xuexiaoyi.xxy
  - PROCESS-NAME,com.android.providers.calendar
  - PROCESS-NAME,me.zhanghai.android.files
  - PROCESS-NAME,com.baidu.input
  - PROCESS-NAME,com.miui.mishare.connectivity
  - PROCESS-NAME,com.lbe.security.miui
  - PROCESS-NAME,com.miui.thirdappassistant
  - PROCESS-NAME,com.miui.voiceassist
  - PROCESS-NAME,com.mi.liveassistant
  - PROCESS-NAME,com.xiaomi.scanner
  - PROCESS-NAME,com.miui.contentextension
  - PROCESS-NAME,com.miui.securitycenter
  - PROCESS-NAME,com.miui.vpnsdkmanager
  - PROCESS-NAME,com.miui.smsextra
  - PROCESS-NAME,com.miui.backup
  - PROCESS-NAME,com.miui.cloudbackup
  - PROCESS-NAME,me.app.xad
  - PROCESS-NAME,com.android.managedprovisioning
  - PROCESS-NAME,com.miui.translationservice
  - PROCESS-NAME,com.xiaomi.mircs
  - PROCESS-NAME,com.miui.accessibility
  - PROCESS-NAME,com.miui.gallery
  - PROCESS-NAME,com.android.email
  - PROCESS-NAME,com.eg.android.AlipayGphone
  - PROCESS-NAME,com.xiaomi.mibrain.speech
  - PROCESS-NAME,android
  - PROCESS-NAME,com.xiaomi.misettings
  - PROCESS-NAME,com.xiaomi.mimobile.noti
  - PROCESS-NAME,com.xiaomi.miplay_client
  - PROCESS-NAME,com.xiaomi.metoknlp
  - PROCESS-NAME,com.sohu.inputmethod.sogou.xiaomi
  - PROCESS-NAME,com.miui.notes
  - PROCESS-NAME,com.miui.newmidrive
  - PROCESS-NAME,com.miui.miservice
  - PROCESS-NAME,com.miui.tsmclient
  - PROCESS-NAME,com.xiaomi.shop
  - PROCESS-NAME,com.neusoft.smartcity.henan
  - PROCESS-NAME,com.android.provision
  - PROCESS-NAME,com.taobao.taobao
  - PROCESS-NAME,com.android.proxyhandler
  - PROCESS-NAME,com.android.browser
  - PROCESS-NAME,com.alibaba.android.rimet
  - PROCESS-NAME,com.android.providers.downloads
  - PROCESS-NAME,com.xiaomi.mico
  - PROCESS-NAME,org.hello.coolapk
  - PROCESS-NAME,com.miui.powerkeeper
  - PROCESS-NAME,com.miui.video
  - PROCESS-NAME,com.android.bluetooth
  - PROCESS-NAME,cn.wps.moffice_eng
  - PROCESS-NAME,com.xiaomi.mi_connect_service
  - PROCESS-NAME,com.miui.personalassistant
  - PROCESS-NAME,com.miui.securityadd
  - PROCESS-NAME,com.xiaomi.gamecenter.sdk.service
  - PROCESS-NAME,com.android.providers.downloads.ui
  - PROCESS-NAME,com.qualcomm.qti.cne
  - PROCESS-NAME,com.miui.miwallpaper.snowmountain
  - PROCESS-NAME,com.baidu.input_mi
  - PROCESS-NAME,org.swiftapps.swiftbackup
  - PROCESS-NAME,com.google.android.apps.authenticator2
  - PROCESS-NAME,com.absinthe.anywhere_
  - PROCESS-NAME,com.xiaomi.xmsf
  - PROCESS-NAME,com.google.android.configupdater
  - PROCESS-NAME,com.android.dynsystem
  - PROCESS-NAME,com.android.htmlviewer
  - PROCESS-NAME,com.miui.yellowpage
