name: Convert Format

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    # this Action should follow steps to set up Python build environment
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: "code/requirements.txt"

    - name: update list
      run: |
        python code/yaml2list.py

    - name: commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "update"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
